### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by mjiong** [liukaijv/laravel-vue-cms#1]
执行了npm run build后就如下error，请问是什么原因呢？

**[BABEL] Note: The code generator has deoptimised the styling of "/home/myuser/web/laravel_cms/resources/admin/assets/js/plugins/select2/select2.js" as it exceeds the max of "100KB".**

**Comment by liukaijv** [comment]
这个是select2.js超过100kb了的提示信息，程序能不能运行呢？
http://stackoverflow.com/questions/31690481/grunt-babel-100-kb-styling-issue
